Autotracing - Clinical step phase start greater than phase end bug
jshmrtn/hygeia pull request #1006
Opened 2021-12-13 13:59 UTC by atoncetti

Implementation of [#992](https://github.com/jshmrtn/hygeia/issues/992) and duplicate [#995](https://github.com/jshmrtn/hygeia/issues/995).

TODO: Check that start and end phase logic follows requirements

2021-12-13 16:39 UTC, janmrnak commented on lib/hygeia/case_context/case.ex
> +      |> Enum.sort({:asc, Date})
I think, this is not sorted on purpose -> meaning as start you take the first date that exists

2021-12-13 16:42 UTC, janmrnak commented on lib/hygeia/case_context/case.ex
> +          _lt_eq -> {:ok, symptom_start}
Here I would say Jony wants to use it as an additional check -> match error if there is other result

2021-12-13 16:47 UTC, janmrnak commented
For the problem, I think there is nothing wrong with the implementation, but there could be problem with wrong data before changing the implementation...

2021-12-14 08:59 UTC, maennchen requested changes

2021-12-14 08:59 UTC, maennchen commented on lib/hygeia/case_context/case.ex
>            :gt -> {:corrected, earliest_start_date}
The code before was more specific. As long as you're not changing anything, I would revert this change.

2021-12-14 08:59 UTC, maennchen commented on lib/hygeia_web/live/auto_tracing_live/clinical.ex
> +    phase_end =
That can't be the solution that the tracing came up with. This just adds 20 days instead of 10.

The same bug can be triggered as before (just a bit longer time needed) and we can't quarantine people for more than 10 days.

2021-12-14 08:59 UTC, maennchen commented on test/hygeia_web/live/auto_tracing_live_test.exs
> +          %{clinical: nil}
That changes all tests. Is that intended?

2021-12-20 11:14 UTC, atoncetti commented on test/hygeia_web/live/auto_tracing_live_test.exs
> +          %{clinical: nil}
Yes, we change clinical information only in the clinical step. The case fixture presets a has symptoms, symptom start date and therefore all tests can pass (for example, setting has symptoms to true and no symptom start date in a test would pass)

2021-12-21 10:30 UTC, maennchen commented on lib/hygeia/case_context/case/clinical.ex
>          changeset
only return the changeset

2021-12-21 10:30 UTC, maennchen commented on lib/hygeia/case_context/case/clinical.ex
>          Ecto.Changeset.put_change(changeset, :symptoms, nil)
```suggestion
        Ecto.Changeset.put_change(changeset, :symptoms, [])
```

2021-12-21 14:36 UTC, maennchen approved these changes

2021-12-21 14:37 UTC, merged