User Pruning
jshmrtn/hygeia pull request #1539
Opened 2022-07-24 19:49 UTC by janmrnak

Implementation of #1415

2022-07-25 08:18 UTC, maennchen requested changes

2022-07-25 08:18 UTC, maennchen commented on lib/hygeia/jobs/data_pruning.ex
> +  defp execute_prune(:user_pruning) do
We can't delete users since they might be used in places. That's why we only anonymize.

2022-07-25 08:18 UTC, maennchen commented on lib/hygeia/jobs/user_sync.ex
> +    if (Enum.empty?(user.grants) and Enum.empty?(attrs.grants)) or
We want to do the opposite. If the grants are empty, we need to anonymize right then.

2022-07-25 08:18 UTC, maennchen commented on lib/hygeia/user_context/user.ex
> +    user
Check `email` if `fetch_field!(changeset, :grants) != []`. Do not match on the changeset params.

2022-07-25 08:18 UTC, maennchen commented on lib/hygeia/user_context/user.ex
> +  def anonymize_user_attrs_as_needed(%{grants: []} = attrs),
Do this directly in the changeset.

2022-07-25 08:43 UTC, janmrnak commented on lib/hygeia/jobs/data_pruning.ex
> +  defp execute_prune(:user_pruning) do
correct, it's maybe wrong named, but it is deleting "versions" not users, if it would be possible to get to User.show, then there will be the name and email in versions.

2022-07-25 08:46 UTC, janmrnak commented on lib/hygeia/jobs/user_sync.ex
> +    if (Enum.empty?(user.grants) and Enum.empty?(attrs.grants)) or
so that is why, we do anonymize only when attrs.grants (change) are empty but user.grants not yet

2022-07-25 09:45 UTC, maennchen commented on lib/hygeia/jobs/data_pruning.ex
> +  defp execute_prune(:user_pruning) do
We don't need it

2022-07-26 15:35 UTC, maennchen approved these changes

2022-07-26 15:35 UTC, merged