Case Daily Statistics
jshmrtn/hygeia pull request #358
Opened 2021-07-19 14:38 UTC by janmrnak

Implementation of #330

2021-07-19 14:53 UTC, maennchen requested changes

2021-07-19 14:53 UTC, maennchen commented on apps/hygeia/lib/hygeia/statistics_context/new_registered_cases_per_day.ex
> +  defenum Type, :case_phase_type, [
Why are you not using `Hygeia.CaseContext.Case.Phase.Type`?

2021-07-19 14:53 UTC, maennchen commented on apps/hygeia/lib/hygeia/statistics_context/new_registered_cases_per_day.ex
> +            }
```suggestion
  @type t ::
          %__MODULE__{
            count: non_neg_integer(),
            date: Date.t(),
            type: Type.t(),
            first_contact: boolean,
            tenant_uuid: Ecto.UUID.t(),
            tenant: Ecto.Schema.belongs_to(Tenant.t())
          }
```

2021-07-19 14:53 UTC, maennchen commented on apps/hygeia/priv/repo/migrations/20210719100312_statistics_new_registered_cases_per_day.exs
> +          cases.inserted_at::date AS count_date,
use phase insertion date, not the one from the case

otherwise a case where a new phase is appended will count on the case creation date

2021-07-19 14:53 UTC, maennchen commented on apps/hygeia/priv/repo/migrations/20210719100312_statistics_new_registered_cases_per_day.exs
> +          END AS first_contact
```suggestion
          cases.status = 'first_contact' AS first_contact
```

2021-07-19 14:53 UTC, maennchen commented on apps/hygeia/priv/repo/migrations/20210719100312_statistics_new_registered_cases_per_day.exs
> +          COUNT(DISTINCT phases.person_uuid) AS count
Since every phase produces work, we'd like to count the phases and not people

2021-07-19 14:53 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/statistics_live/daily_statistics.sface
> +                    %{type: :index} ->
```suggestion
                    %NameOfModule{type: :index} ->
```

2021-07-19 14:53 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/statistics_live/timeline.sface
> +                  end)
```suggestion
                  |> Enum.reduce(%{}, fn %NameOfModule{date: date, count: count, type: type}, acc ->
                    entry = %{
                      x: date |> DateTime.new!(~T[00:00:00]) |> DateTime.to_unix(:millisecond),
                      y: count
                    }
            
                    Map.update(acc, type, [entry], &[entry | &1])
                  end)
                  |> Enum.map(fn
                    {:index, entries} ->
                      %{
                        label: gettext("Index"),
                        fill: %{target: "origin"},
                        data: Enum.reverse(entries)
                      }
            
                    {:possible_index, entries} ->
                      %{
                        label: gettext("Possible Index"),
                        fill: %{target: "origin"},
                        data: Enum.reverse(entries)
                      }
                  end)
```

2021-07-20 08:19 UTC, janmrnak commented on apps/hygeia/priv/repo/migrations/20210719100312_statistics_new_registered_cases_per_day.exs
> +          cases.inserted_at::date AS count_date,
We don't have phase insertion date.

2021-07-20 08:31 UTC, maennchen commented on apps/hygeia/priv/repo/migrations/20210719100312_statistics_new_registered_cases_per_day.exs
> +          cases.inserted_at::date AS count_date,
Then we should add that. For all the old cases we fall back to the inserted_at of the case.

2021-07-20 15:27 UTC, maennchen submitted a review, later dismissed

2021-07-20 15:44 UTC, maennchen approved these changes

2021-07-20 15:45 UTC, merged