Refactoring create possible index
jshmrtn/hygeia pull request #433
Opened 2021-08-21 01:02 UTC by atoncetti

Known issues:

- Creating a new case with status closed with any transmission type other than :travel, :contact_person gives an error.

Missing implementation:

- add navigation blocking in the form steps

2021-08-23 08:27 UTC, maennchen commented
@atoncetti Please set up a global gitignore: https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

Ignore `.elixir_ls` in there and remove it from this PR.

(YOu can use that global gitignore for all IDE files / Operating System specific stuff like `.DS_Store`)

2021-08-23 08:28 UTC, maennchen commented
@atoncetti If you're not changing the CSS / JS, I would not expect any changes in the `package-lock.json`. Please revert.

2021-08-23 08:46 UTC, maennchen requested changes
This is only a partial review so far, more is coming later when I have more time.

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia/lib/hygeia/communication_context.ex
> +
I assume you added this function so that you can specify the number. If you do that, please refactor `create_outgoing_sms/2` so that it uses the same function.

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia/lib/hygeia/communication_context.ex
> +
(same for email)

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/helpers/changeset.ex
> +    do: Changeset.fetch_field!(changeset, :inserted_at) != nil
```suggestion
  def existing_entity?(%Changeset{data: entity} = _changeset),
    do: Ecto.get_meta(entity, :state) == :loaded
```

Docs:

* https://hexdocs.pm/ecto/Ecto.html#get_meta/2
* https://hexdocs.pm/ecto/Ecto.Schema.Metadata.html#module-state

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/helpers/field_name.ex
> +    HygeiaWeb.CaseLive.CreatePossibleIndex.FormStep.DefineOptions => %{
Please order the modules alphabetically.

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/helpers/form_step.ex
> +    end
```suggestion
    case get_step(steps, current_step_name) do
      %__MODULE__{^direction => desired_step_name} -> desired_step_name
      nil -> nil
    end
```

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.ex
> +  defp save(socket) do
```suggestion
  defp save(%Phoenix.Socket{assigns: %{current_form_data: %{bindings: bindings} = current_form_data}} = socket) do
```

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.ex
> +      :comment => comment,
Use the short version if you only have atom keys.

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/case_snippet.ex
> +  prop case_changeset, :map, default: nil
Mark props / slots as required when they are required.

2021-08-23 08:46 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/case_snippet.sface
> +                      {!-- TODO: a date should be shown, but which one? A phase has no inserted_at. --}
https://github.com/jshmrtn/hygeia/blob/96cfbbaf1627569b2d23944a7a141faa98af7e98/apps/hygeia/lib/hygeia/case_context/case/phase.ex#L62

Since this is a new addition, fall back to case inserted_at

2021-08-23 10:37 UTC, maennchen requested changes

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.sface
> +      <div class="row">
Prefer the inline version of `if`/ `for` as long as it is possible

```suggestion
      <div class="row" :if={@form_step != "summary"}>
```

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/form_step/define_options.ex
> +  end
```suggestion
  data bindings, :list, default: []
  data loading, :boolean, default: false
```

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/form_step/define_options.ex
> +    bindings = Map.get(data, :bindings, [])
extract via function header pattern matching

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/form_step/define_options.ex
> +    %{assigns: %{bindings: bindings}} = socket
match in header

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/form_step/define_transmission.ex
> +  end
```suggestion
  data loading, :boolean, default: false
  data changeset, :map

  @impl Phoenix.LiveComponent
  def mount(socket) do
    {:ok,
     assign(socket,
       changeset: changeset(%__MODULE__{})
     )}
  end
```

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/form_step/reporting.ex
> +  def mount(socket) do
`data`

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/test/support/case_live_test_helper.ex
> +    %{conn: conn} = context
```suggestion
  def test_transmission_step_type_travel(view, %{conn: conn}) do
```

2021-08-23 10:37 UTC, maennchen commented on config/dev.exs
> +config :logger, level: :info
Could you make a permanent change?

* Remove all log levels from `dev/prod/test` config
* Add Log Level to `runtime.exs`
* Document Env Variable in the `.env.example`


```elixir
config, :logger, level: String.to_atom(System.get_env("LOG_LEVEL", case config_env() do
  :prod -> "info"
  :dev -> "debug"
  :test -> "debug"
end))
```

This way it is easier to change the level (for example in dev, you can just run `LOG_LEVEL="warn" iex -S mix phx.server`)

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
> +       bindings: [],
`data`

2021-08-23 10:37 UTC, maennchen commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
> +    %{
move to head. when extracting a struct, always use `%Struct{} = var` and not `%{} = var` to get compile time checks on the fields

2021-08-23 12:39 UTC, atoncetti commented on apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.sface
> +      <div class="row">
The [Surface documentation](https://surface-ui.org/template_syntax#directives) now suggests the 'for block' version because they plan to remove the inline version in the future, wondering if they'll do the same for :if? Your recommendation?

2021-11-10 17:24 UTC, maennchen commented on config/runtime.exs
> +api_port =
api is nno longer required. this is probably a merge error

2021-11-10 17:28 UTC, maennchen requested changes

2021-11-10 17:28 UTC, maennchen commented on lib/hygeia_web/live/case_live/create_possible_index/form_step/define_contact_methods.ex
> +          should_feed ->
`should_feed` is unused

2021-11-10 17:33 UTC, maennchen commented on lib/hygeia_web/live/case_live/create_possible_index.sface
> -                      <label class={
Active Label seems not to work. The one for `true` / `false` works though.

2021-11-10 17:40 UTC, maennchen commented
## Test Scenarios

<details><summary>

*✕ Create New Case with new person*

</summary>

### Steps

* Type: `contact`
* Date: yesterday
* Person Details: any new details (no duplicates detected)
* No changes
* Save

### Expected

* [ ] No Error / Warnings - Issue: https://joshmartin.slack.com/archives/D026X68BLDR/p1636565822005300
* [X] Case is created
* [X] Case has contact phase
* [X] quarantine is ordered
* [X] start / end are calculated based on current date / contact date
 
</details>

2021-11-12 08:52 UTC, atoncetti commented on lib/hygeia_web/live/case_live/create_possible_index.ex
> +                if(not is_nil(employer) and String.length(employer) > 0,
Checking length is not required

2021-11-12 08:57 UTC, maennchen commented on lib/hygeia_web/live/case_live/create_possible_index.ex
> +                if(not is_nil(employer) and String.length(employer) > 0,
Sorry, One small thing I forgot: We support unknown organisations by now.

Therefore this might be better:

```elixir
                  do: [%{unknown_organisation: %{name: employer}}]
```

2021-11-15 15:40 UTC, maennchen commented on lib/hygeia_web/live/case_live/create_possible_index.ex
> +      step_name -> String.to_atom(step_name)
```suggestion
      step_name -> String.to_existing_atom(step_name)
```

2021-11-16 08:06 UTC, maennchen commented on lib/hygeia_web/helpers/form_step.ex
> +          prev: String.t() | atom() | nil,
Can't be a sting anymore, right?

2021-11-16 08:27 UTC, lzurbriggen commented on lib/hygeia_web/helpers/form_step.ex
> +          prev: String.t() | atom() | nil,
It's a generic helper and I wasn't sure if it needed to support both, I changed it for now.

2021-11-19 09:59 UTC, maennchen approved these changes

2021-11-19 10:00 UTC, merged